### PR TITLE
Chaapter -> Chapter

### PR DESCRIPTION
**Pull request by MatthewCaseres**

### CODE REVIEW

**Review by arleym — APPROVED** [review]
The beauty and the curse of automating is one typo can turn into many! 

Thank you so much for this!

**Comment by MatthewCaseres** [comment]
> The beauty and the curse of automating is one typo can turn into many!
> 
> Thank you so much for this!

Thank you for putting this out there in an easy to read format! I'm hosting the markdown on my website.

https://www.openedtech.dev/Open-EdTech/kjv-markdown/01-Genesis-KJV.md

**Comment by arleym** [comment]
That is super cool! I've never seen markdown directly in the browser
before... makes me wish there had been a simple way to denote a class on a
verse number.

I use markdown for my "digital bible" (which I use in Sublime text),
primarily the ESV which I can't share publicly for copyright reasons.
Currently I'm working on the WEB translation since it's also freely
shareable.

[image: image.png]

Arley McBlain
http://arleym.com

**Comment by MatthewCaseres** [comment]
I'm using MDX which converts Markdown to React, I made a package that loads Markdown repositories from GitHub and turns them into e-books.

You can totally process the markdown with a markdown processor (via unifiedjs), and embed each verse as a custom react or HTML element (I use react with MDX). I'm playing around with headers/paragraphs that can detect when they are on-screen to provide an 'auto-bookmark' feature. 

I converted the Catholic Public Domain Version bible, but I guess it isn't endorsed by the Catholic Church. If I get the time to convert another one I would do the Douay-Rheims.

**Comment by arleym** [comment]
So cool. My background is more design/UI/web accessibility focussed, so I
tend to shy away from JS and React type stuff... heck, today I just merged
my first pull request on Github ;)

Way off topic; but have you ever seen markdown files generate something
more complicated, like a calendar? I was day-dreaming about using an
Obsidian.md vault as a GTD (Getting Things Done) to do list system! One
file would [[link]] to all the tasks, and build into a viewable calendar...
I'm guessing it's an idea that requires hacky hoop-jumping, but Notion's
outage / lack of offline storage got me thinking about it! I'm not asking
you to lift a finger, just for your gut-feeling on it / what I could google
haha

Arley McBlain
http://arleym.com

**Comment by MatthewCaseres** [comment]
Edit: Maybe check obsidian plugins? I give a general description of my general approach to processing Markdown below though. Obsidian plugins seem pretty interesting.

Probably a few ways to accomplish this, but I think for this task you might not need to generate a UI?

It sounds like you are comfortable using the text editor as your interface for tasks, so I think being able to generate summary files of your text might help you understand what is going on in your personal organization system? 

The exact approach I would use is to embed custom code blocks throughout my text files with a language tag of `ToDo`. So you put these things wherever you want:

```ToDo
description: This is some stuff I want to do.
completedAt: ~
```

The tilde is YAML syntax for `null`. Maybe just run `Date.now()` in your console when you finish the task to generate the completion time.

```ToDo
description: Another thing.
completedAt: 1609914397402
```

Now we need some JS grab all of our ToDo files. Basically use Node.js to iterate over all the files in the specified directory. You can give your files containing ToDo tags a 'Todo' suffix (CarWashToDo.md) and only search those if ToDo files are sharing directories with non-ToDo files. Use a unified.js parser and grab all the code blocks with lang === 'ToDo' and write them to a file, you can sort by completedAt or separate completed and not completed.

Maybe have some sort of JSON validation step to ensure all of your tags contain certain required fields just to avoid the temptation to change your data definitions on a whim, which would be bad for data quality.

The first thing to do would be to learn how to read YAML code blocks from a markdown file using unified.js, js-yaml, node.js, and rewrite them to another markdown file after some processing. Just do that for all the files in a directory and you're finished.

Curious if this would meet your requirements? You could generate a UI but it involves a dive into React-land, and I think keeping things as text files makes sense for Obsidian.

**Comment by MatthewCaseres** [comment]
Ooh I have an idea. A blog generator that works with Obsidian.

**Comment by arleym** [comment]
Some kind of publishing tool will be coming with it somehow! You've given
me much to google, so thank you for that too!

Arley McBlain
http://arleym.com

**Comment by MatthewCaseres** [comment]
I like to roll my own stuff though, don't like being stuck in someone's ecosystem (especially if they want money!). I'll send you the link if I ever get around to building a blog based on my daily obsidian notes. Thanks for the tip on Obsidian, I had heard of it but hadn't taken the time to read the docs.

**Pull request merged**
